# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(default='Hard working')),
                ('registration_date', models.DateField(default=datetime.date(2017, 1, 1))),
                ('graduation_date', models.DateField(default=datetime.date(2017, 1, 1))),
            ],
        ),
    ]
