# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychall', '0003_auto_20170704_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='position',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(default='Disciplined'),
        ),
    ]
